spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/whatToEatToday
    username: hj
    password: hj
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
<<<<<<< Updated upstream
      ddl-auto: create
=======
      ddl-auto: none
>>>>>>> Stashed changes
    properties:
      hibernate:
  # show_sql: true
        format_sql: true
logging.level:
  org.hibernate.SQL: debug
# org.hibernate.type: trace